################################### Cluster ###################################
cluster.name: production

#################################### Index ####################################
index:
  analysis:
    analyzer:
      bg_analyzer:
        type: custom
        tokenizer: icu_tokenizer
        filter: [icu_folding, icu_normalizer, bg_stop_filter, bg_stem_filter]
      cs_analyzer:
        type: custom
        tokenizer: icu_tokenizer
        filter: [icu_folding, icu_normalizer, cs_stop_filter, cs_stem_filter]
      da_analyzer:
        type: custom
        tokenizer: icu_tokenizer
        filter: [icu_folding, icu_normalizer, da_stop_filter, da_stem_filter]
      de_analyzer:
        type: custom
        tokenizer: icu_tokenizer
        filter: [icu_folding, icu_normalizer, de_stop_filter, de_stem_filter]
      default_analyzer:
        type: custom
        tokenizer: standard
        filter: [standard, lowercase]
      el_analyzer:
        type: custom
        tokenizer: icu_tokenizer
        filter: [icu_folding, icu_normalizer, el_stop_filter]
      en_analyzer:
        type: custom
        tokenizer: icu_tokenizer
        filter: [icu_folding, icu_normalizer, en_stop_filter, en_stem_filter]
      es_analyzer:
        type: custom
        tokenizer: icu_tokenizer
        filter: [icu_folding, icu_normalizer, es_stop_filter, es_stem_filter]
      fi_analyzer:
        type: custom
        tokenizer: icu_tokenizer
        filter: [icu_folding, icu_normalizer, fi_stop_filter, fi_stem_filter]
      fr_analyzer:
        type: custom
        tokenizer: icu_tokenizer
        filter: [icu_folding, icu_normalizer, fr_stop_filter, fr_stem_filter]
      hu_analyzer:
        type: custom
        tokenizer: icu_tokenizer
        filter: [icu_folding, icu_normalizer, hu_stop_filter, hu_stem_filter]
      it_analyzer:
        type: custom
        tokenizer: icu_tokenizer
        filter: [icu_folding, icu_normalizer, it_stop_filter, it_stem_filter]
      nl_analyzer:
        type: custom
        tokenizer: icu_tokenizer
        filter: [icu_folding, icu_normalizer, nl_stop_filter, nl_stem_filter]
      pt_analyzer:
        type: custom
        tokenizer: icu_tokenizer
        filter: [icu_folding, icu_normalizer, pt_stop_filter, pt_stem_filter]
      ro_analyzer:
        type: custom
        tokenizer: icu_tokenizer
        filter: [icu_folding, icu_normalizer, ro_stop_filter, ro_stem_filter]
      sv_analyzer:
        type: custom
        tokenizer: icu_tokenizer
        filter: [icu_folding, icu_normalizer, sv_stop_filter, sv_stem_filter]

    filter:
      bg_stop_filter:
        type: stop
        stopwords: [_bulgarian_]
      bg_stem_filter:
        type: stemmer
        name: bulgarian
      cs_stop_filter:
        type: stop
        stopwords: [_czech_]
      cs_stem_filter:
        type: stemmer
        name: czech
      da_stop_filter:
        type: stop
        stopwords: [_danish_]
      da_stem_filter:
        type: stemmer
        name: danish
      de_stop_filter:
        type: stop
        stopwords: [_german_]
      de_stem_filter:
        type: stemmer
        name: german
      el_stop_filter:
        type: stop
        stopwords: [_greek_]
      el_stem_filter:
        type: stemmer
        name: greek
      en_stop_filter:
        type: stop
        stopwords: [_english_]
      en_stem_filter:
        type: stemmer
        name: minimal_english
      es_stop_filter:
        type: stop
        stopwords: [_spanish_]
      es_stem_filter:
        type: stemmer
        name: spanish
      fr_stop_filter:
        type: stop
        stopwords: [_french_]
      fr_stem_filter:
        type: stemmer
        name: minimal_french
      fi_stop_filter:
        type: stop
        stopwords: [_finnish_]
      fi_stem_filter:
        type: stemmer
        name: finnish
      hu_stop_filter:
        type: stop
        stopwords: [_hungarian_]
      hu_stem_filter:
        type: stemmer
        name: hungarian
      it_stop_filter:
        type: stop
        stopwords: [_italian_]
      it_stem_filter:
        type: stemmer
        name: italian
      nl_stop_filter:
        type: stop
        stopwords: [_dutch_]
      nl_stem_filter:
        type: stemmer
        name: dutch
      pt_stop_filter:
        type: stop
        stopwords: [_portuguese_]
      pt_stem_filter:
        type: stemmer
        name: portuguese
      ro_stop_filter:
        type: stop
        stopwords: [_romanian_]
      ro_stem_filter:
        type: stemmer
        name: romanian
      sv_stop_filter:
        type: stop
        stopwords: [_swedish_]
      sv_stem_filter:
        type: stemmer
        name: swedish

#################################### Paths ####################################
path:
  logs: /var/log/elasticsearch
  data: /var/local/es/data

############################## Network And HTTP ###############################
http:
  port: 9400
  jsonp:
    enable: true

transport:
  tcp:
    port: 9500
