#!/bin/sh

#
# chkconfig: 35 99 99
# description: EEA SEARCH dev Node.js
#

. /etc/rc.d/init.d/functions

USER="root"

DAEMON="/var/local/nodejs/bin/node"
ROOT_DIR="/var/local/es-dev/eea.elasticsearch/webapps/eea_search"

SERVER="$ROOT_DIR/eea_search.js"
LOG_FILE="/var/log/eea-search-dev.js.log"
ERR_FILE="/var/log/eea-search-dev.err.log"

LOCK_FILE="/var/lock/subsys/node-eea-search-dev"

do_start()
{
        if [ ! -f "$LOCK_FILE" ] ; then
                echo -n $"Starting $SERVER: "
                cd $ROOT_DIR
                su -m "$USER" -c "$DAEMON $SERVER dev >> $LOG_FILE 2>> $ERR_FILE &" && echo_success || echo_failure
                RETVAL=$?
                echo
                [ $RETVAL -eq 0 ] && touch $LOCK_FILE
        else
                echo "$SERVER is locked."
                RETVAL=1
        fi
}
do_stop()
{
        echo -n $"Stopping $SERVER: "
        pid=`ps -aefw | grep "$DAEMON $SERVER dev" | grep -v " grep " | awk '{print $2}'`
        kill -9 $pid > /dev/null 2>&1 && echo_success || echo_failure
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && rm -f $LOCK_FILE
}

case "$1" in
        start)
                do_start
                ;;
        stop)
                do_stop
                ;;
        restart)
                do_stop
                do_start
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                RETVAL=1
esac

exit $RETVAL
