curl -u eea:eea -XPUT 'http://centaurus-dev.eea.europa.eu/elasticsearch/_river/search1/_meta' -d '{
  "type": "eeaRDF",
  "eeaRDF" : {
    "endpoint" : "http://semantic.eea.europa.eu/sparql",
    "queryType" : "construct",
    "query" : "CONSTRUCT {?s ?p ?o} WHERE {{ ?s a <http://www.eea.europa.eu/portal_types/Highlight#Highlight> . ?s ?p ?o} UNION {?s a <http://www.eea.europa.eu/portal_types/KeyMessage#KeyMessage> . ?s ?p ?o}  UNION { ?s a <http://www.eea.europa.eu/portal_types/MethodologyReference#MethodologyReference> . ?s ?p ?o } UNION {?s a <http://www.eea.europa.eu/portal_types/Organisation#Organisation> . ?s ?p ?o} UNION {?s a <http://www.eea.europa.eu/portal_types/PolicyDocumentReference#PolicyDocumentReference> . ?s ?p ?o} UNION {?s a <http://www.eea.europa.eu/portal_types/PolicyQuestion#PolicyQuestion> . ?s ?p ?o} UNION {?s a <http://www.eea.europa.eu/portal_types/PressRelease#PressRelease> . ?s ?p ?o} UNION {?s a <http://www.eea.europa.eu/portal_types/RationaleReference#RationaleReference> . ?s ?p ?o} UNION {?s a <http://www.eea.europa.eu/portal_types/Report#Report> . ?s ?p ?o} UNION {?s a <http://www.eea.europa.eu/portal_types/SOERKeyFact#SOERKeyFact> . ?s ?p ?o} UNION {?s a <http://www.eea.europa.eu/portal_types/SOERMessage#SOERMessage> . ?s ?p ?o} }",
	"normProp" : { "http://www.eea.europa.eu/portal_types/Assessment#themes" : "topic", "http://www.eea.europa.eu/portal_types/AssessmentPart#themes" : "topic", "http://www.eea.europa.eu/portal_types/Data#themes" : "topic", "http://www.eea.europa.eu/portal_types/CloudVideo#themes" : "topic", "http://www.eea.europa.eu/portal_types/DataFile#themes" : "topic", "http://www.eea.europa.eu/portal_types/DavizVisualization#themes" : "topic", "http://www.eea.europa.eu/portal_types/Document#themes" : "topic", "http://www.eea.europa.eu/portal_types/EEAFigureFile#themes" : "topic", "http://www.eea.europa.eu/portal_types/EEAVacancy#themes" : "topic", "http://www.eea.europa.eu/portal_types/EcoTip#themes" : "topic", "http://www.eea.europa.eu/portal_types/EpubFile#themes" : "topic", "http://www.eea.europa.eu/portal_types/Event#themes" : "topic", "http://www.eea.europa.eu/portal_types/ExternalDataSpec#themes" : "topic", "http://www.eea.europa.eu/portal_types/EyewitnessStory#themes" : "topic", "http://www.eea.europa.eu/portal_types/FactSheetDocument#themes" : "topic", "http://www.eea.europa.eu/portal_types/File#themes" : "topic", "http://www.eea.europa.eu/portal_types/Highlight#themes" : "topic", "http://www.eea.europa.eu/portal_types/Image#themes" : "topic", "http://www.eea.europa.eu/portal_types/IndicatorFactSheet#themes" : "topic", "http://www.eea.europa.eu/portal_types/KeyMessage#themes" : "topic", "http://www.eea.europa.eu/portal_types/Link#themes" : "topic", "http://www.eea.europa.eu/portal_types/MethodologyReference#themes" : "topic", "http://www.eea.europa.eu/portal_types/Organisation#themes" : "topic", "http://www.eea.europa.eu/portal_types/PolicyDocumentReference#themes" : "topic", "http://www.eea.europa.eu/portal_types/PolicyQuestion#themes" : "topic", "http://www.eea.europa.eu/portal_types/PressRelease#themes" : "topic", "http://www.eea.europa.eu/portal_types/Promotion#themes" : "topic", "http://www.eea.europa.eu/portal_types/QuickEvent#themes" : "topic", "http://www.eea.europa.eu/portal_types/RationaleReference#themes" : "topic", "http://www.eea.europa.eu/portal_types/Report#themes" : "topic", "http://www.eea.europa.eu/portal_types/SOERKeyFact#themes" : "topic", "http://www.eea.europa.eu/portal_types/SOERMessage#themes" : "topic", "http://www.eea.europa.eu/portal_types/Specification#themes" : "topic", "http://www.eea.europa.eu/portal_types/Speech#themes" : "topic", "http://www.eea.europa.eu/portal_types/WorkItem#themes" : "topic"},
	"proplist" : ["http://www.w3.org/1999/02/22-rdf-syntax-ns#type", "http://purl.org/dc/terms/spatial", "http://purl.org/dc/terms/creator", "http://purl.org/dc/terms/issued", "http://purl.org/dc/terms/title", "http://www.w3.org/1999/02/22-rdf-syntax-ns#about", "language", "topic"],
    "listtype" : "white",
    "blackMap" : {"http://www.w3.org/1999/02/22-rdf-syntax-ns#type" : ["Webpage", "Tracked file"]},
    "normObj" : {"Organisation" : "Organization", "Quick Event" : "Event"}
}}'

