curl -u eea:eea -XDELETE 'http://centaurus-dev.eea.europa.eu/elasticsearch/_river/search0'
curl -u eea:eea -XDELETE 'http://centaurus-dev.eea.europa.eu/elasticsearch/_river/search1'
curl -u eea:eea -XDELETE 'http://centaurus-dev.eea.europa.eu/elasticsearch/_river/search2'
curl -u eea:eea -XDELETE 'http://centaurus-dev.eea.europa.eu/elasticsearch/_river/search3'
curl -u eea:eea -XDELETE 'http://centaurus-dev.eea.europa.eu/elasticsearch/_river/search4'
curl -u eea:eea -XDELETE 'http://centaurus-dev.eea.europa.eu/elasticsearch/_river/search5'
curl -u eea:eea -XDELETE 'http://centaurus-dev.eea.europa.eu/elasticsearch/_river/search6'
curl -u eea:eea -XDELETE 'http://centaurus-dev.eea.europa.eu/elasticsearch/_river/search7'
